### ISSUE TITLE
Data Viewer: Fix Level 1 Salmon headings

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/madrona-priorities#82]
In the Data Viewer, salmon are broken up into three separate tabs: 
• Species, Widespread: Salmon
• Widespread: Salmon
• Species, Species, Widespread: Salmon

All data layers for salmon should be under the heading  "Species, Widespread: Salmon"

I can fix it in flat blocks but it will take some time. Is there a quick way for you to fix this?

**Comment by rhodges** [comment]
I see 18 layers that need to be changed - doing this with windows side by side (Django Admin in one screen, live site in the other)  I think would take 10-15 minutes. Doing this with python would also take 10-15 minutes, but wouldn't be without risk (more authentication and integrity checks are performed when run through the site).

I can do it if you'd like, but if I'm doing it, I'll do it through the Django Admin, not code. After it's done, I can create a fixture so that if we need to update the underlying data again, reorganizing the layers will be quick (though I think we should be able to update the data without issues once this is done.)

**Comment by rhodges** [comment]
I admit @jtutak , this was more work than anticipated and only fixed in the end via a bit of a hack. Ugh. Thanks for the help and patience!
